Drivers
BitMask-Technologies/route-lift-api pull request #12
Opened 2021-06-24 08:04 UTC by bencipher

2021-06-24 16:12 UTC, KIngSimeone commented
@DeeMATT

2021-06-25 17:55 UTC, DeeMATT requested changes
Thanks bruv @bencipher . I made reference to some statements that needs adjustment before I can merge, Kindly help adjust it and we are good to go. Areas with company_id including where I didnt mention it should be corrected as well. Gracias

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/utils.py
> +            company_id=company
Why is the attribute company_id and not company ?

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/utils.py
> +        currentVehicle.company_id = company
company_id isn't necessary because in the model, you specified company.

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +        adminFirstName, adminLastName, adminUsername, adminEmail, adminPhone, adminPassword, company.id, staffRole=adminRole)
Staffs should have a company relation in their model. If that is so, we ought to pass in the company instance from line 112 not company.id

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +        company = user.company_id
As a reference what I mentioned earlier, the company instance itself and not just the id

user.company_id will give us the ID of the company

We want the vehicles to be properly mapped or related to the company they belong. Hence, we should have;
company = user.company

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
>          vehicles, msg = getAllVehicles()
When we do getAllVehicles(), what parameter is used to determine the company vehicles that are being retrieved from the DB so that we don't just call for all vehicles thereby retrieving vehicles of other companies as well.

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +    company = user.company_id
user.company

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +    # updatedStaff, msg = getStaffById(staff)
We can clean this off since its not been used

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +        currentVehicle, name, make, model, weight, volume, company)
There isn't a need for passing in the company anymore because that will not change until the vehicle is deleted from the system or their records

2021-06-25 17:55 UTC, DeeMATT commented on routelift_api/Users/views.py
> +        staffRole = body.get('staffRole')
I think we are going to have a role already created for riders because their endpoint is dedicated and won't need the staffRole attribute in the request payload

2021-06-25 17:58 UTC, bencipher commented on routelift_api/Logistics/utils.py
> +            company_id=company
Okay boss 🙂 it was simeone that asked me to pass  id instead of objects

2021-06-25 17:59 UTC, bencipher commented on routelift_api/Logistics/views.py
>          vehicles, msg = getAllVehicles()
Okay..... I will adjust that or write another API for that

2021-06-25 18:00 UTC, bencipher commented on routelift_api/Logistics/views.py
> +    # updatedStaff, msg = getStaffById(staff)
I'll mop it off

2021-06-25 18:00 UTC, bencipher commented on routelift_api/Logistics/views.py
> +        currentVehicle, name, make, model, weight, volume, company)
I agree

2021-06-25 18:01 UTC, bencipher commented on routelift_api/Users/views.py
> +        staffRole = body.get('staffRole')
Okay boss

2021-06-25 18:35 UTC, DeeMATT commented on routelift_api/Logistics/utils.py
> +            company_id=company
Okay boss. We want a relational map instead and I don't think that is ideal

2021-06-25 18:37 UTC, DeeMATT commented on routelift_api/Logistics/views.py
>          vehicles, msg = getAllVehicles()
Yes we were suppose to have its own flow but I don't know why Simeone try to put both POST and GET in one single workflow

To be honest, I will prefer a seperate flow instead of relying on if-else condition

2021-06-25 18:38 UTC, DeeMATT commented on routelift_api/Logistics/views.py
>          vehicles, msg = getAllVehicles()
The if-else condition, only accounted for POST method and we are assuming the other should be a GET method

So I ask, what if the user passed in other http methods such as PUT, DELETE, OPTIONS, HEAD and so on

2021-06-25 18:39 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +    # updatedStaff, msg = getStaffById(staff)
Thanks bruv

2021-06-25 18:39 UTC, DeeMATT commented on routelift_api/Logistics/views.py
> +        currentVehicle, name, make, model, weight, volume, company)
U valid

2021-06-26 12:11 UTC, bencipher commented on routelift_api/Logistics/views.py
>          vehicles, msg = getAllVehicles()
I added the IF-ELSE condition, to minimize the endpoints, I discovered that the API get only works for retrieving a single item, so that was why I used it like that, alternatively, I can use the same endpoint for getting single or all items by just checking it the id was passed to retrieve single items

2021-07-01 12:21 UTC, DeeMATT approved these changes

2021-07-01 12:21 UTC, merged